### ISSUE TITLE
Clean up API

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/api#133]
remove obsolete / unnecessary endpoints:

- [ ] `/search/entities` (see #126)
- [ ] `/releases` (see https://github.com/MusicConnectionMachine/api/issues/128#issuecomment-297175381)
- [ ] more?

**Comment by chaoran-chen** [comment]
I think that we should keep `/search/entities` for now, I like it since it's very convenient to use :D

But we should maybe remove `/search` (also known as searchString) and `/autosuggest`, both are not implemented. Besides, I found a function called `todo` in `/controllers/websites.js`, does anyone know what its purpose is / was?

**Comment by Henni** [comment]
@chaoran-chen what do you use the `/search/entities` endpoint for?
In my opinion it looses value as soon as you start using the pagination.
So for the first page it's fine, but afterwards you'll probably want to call the single endpoints instead.

Is it then still worth maintaining the endpoint? And if so, we should probably just reuse the dsap code from the single endpoints.

**Comment by chaoran-chen** [comment]
Okay, well.. if it takes more effort to maintain it than to just keep it, then remove it. But please wait until https://github.com/MusicConnectionMachine/VisualizationG6/issues/104 is finished.
