### ISSUE TITLE
Incorrect initialization

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/api#31]
The [index.js](https://github.com/MusicConnectionMachine/api/blob/develop/index.js#L4) file has two functions that pretty much do the same thing: `getContext` and `connect` both connect to sequelize, so please stick to one, and I suggest `connect`.

This also means that in places like https://github.com/MusicConnectionMachine/api/blob/develop/api/controllers/entities.js#L3 you should change the code to something like:

```javascript
'use strict';

const path = require('path');

var context = require(path.join(__dirname, '../../index.js')).connect(function(context){
    var entities = context.component('dsap').module('entities');
    
   module.exports = {
        getAllEntities: getAllEntities,
        getEntityByID: getEntityByID,
        addEntity: addEntity,
        updateEntity: updateEntity,
        deleteEntity: deleteEntity
    };

    function getAllEntities(req, res) {
        entities.findAllEntities().then(function(list) {
            res.status(200).json(list);
        }).catch(function(error) {
            res.status(500).send(error);
        });
    }
...
});

```

Why? Because this way we know that the execution is only going to happen once the database is connected to and the connection is working.

Also: Instead of loading the connection on every controller, you should define the exports to be a function with an argument, being the context, and then load the controllers with that argument. You did it right [here](https://github.com/MusicConnectionMachine/api/blob/develop/api/dsap/entities.js#L2).
In other words, the above example:

```javascript
'use strict';

const path = require('path');

module.exports = function(context) {
    var entities = context.component('dsap').module('entities');
   
    function getAllEntities(req, res) {
        entities.findAllEntities().then(function(list) {
            res.status(200).json(list);
        }).catch(function(error) {
            res.status(500).send(error);
        });
    }
...

    return {
        getAllEntities: getAllEntities,
        getEntityByID: getEntityByID,
        addEntity: addEntity,
        updateEntity: updateEntity,
        deleteEntity: deleteEntity
    };
});

```

**N.B.: the return is at the end, otherwise the execution will stop before all functions have been declared.**

# Finally,
in your `app.js` file you would like to have a section dedicated to loading all of your controllers (I'm missing how you do this at this time). Some inspiration: https://github.com/efktr/backend/blob/master/app/router.js#L8 in your case, `path.join(__dirname, "services")` would be`path.join(__dirname, "api", "controllers")`

**Comment by ShilpaGhanashyamGore** [comment]
@sacdallago  
1.in your app.js file you would like to have a section dedicated to loading all of your controllers (I'm missing how you do this at this time).  -
[Shilpa]  Invoking the appropriate controller and routing of the requests is handled by swagger-express ( a middleware ) , for eg :  http ://127.0.0.1/artists -  happens from - api\api\swagger\src\paths\artists  has 2 files artists.yml and artist-id yml. 
So the routes equivalent (where express framework is used) is not required in swagger.

2.You should define the exports to be a function with an argument, being the context)Why? Because this way we know that the execution is only going to happen once the database is connected to and the connection is working.
[Shilpa] : I can see all the controllers have the pattern you have mentioned i.e. getting context as a function argument.

**Comment by lukasstreit** [comment]
@sacdallago swagger automatically loads the controllers, which is why we don't have any influence, meaning we have no way of passing a context object to them, iirc.
There could be another way: We can store the context in index.js and return a reference to the initial context when getContext is called again. What do you think?
