### ISSUE TITLE
Get the API online

### ISSUE THREAD

**Issue by pfent** [MusicConnectionMachine/api#99]
Is there an API already setup somewhere?

Ideally this should be running, where the (populated) database is already running.

@MusicConnectionMachine/group-1 can you get this done before the hackathon? Your database is already running somewhere?

**Comment by kordianbruck** [comment]
It should connect to the Postegre Server from @vviro - @Henni has the connection config.

**Comment by Henni** [comment]
I can help with this, if you need help @ShilpaGhanashyamGore

**Comment by ShilpaGhanashyamGore** [comment]
@Henni :Yes  I need help .Please share all the information that is required .What to do as well .I will check in the evening again. Thank you!

**Comment by sacdallago** [comment]
I think this can be done by anyone in @MusicConnectionMachine/group-1 @MusicConnectionMachine/group-2 @MusicConnectionMachine/group-3 or @MusicConnectionMachine/group-4 . You all know how the API works, no need to wait for tonight to have this up and running :) just set up an app service on MS (that's the tool of choice, if I'm not mistaken) and connect it to pg via the env vars :) Please don't wait for @ShilpaGhanashyamGore , if you can do it, do it, would be good for @MusicConnectionMachine/group-5 and @MusicConnectionMachine/group-6 to test out their stuff on real data ;)

**Comment by vviro** [comment]
Please let me know which Dockerfile I should deploy (possible on the same server as the database VM) and I'll do this ASAP.

**Comment by Henni** [comment]
@vviro I'm not completely sure if the docker image is pushed to dockerhub, but in theory it is the dockerfile inside this repository ([reference](https://github.com/MusicConnectionMachine/api/blob/develop/Dockerfile)).
But an important point is, that we are currently working on the API, so it would be necessary to redeploy the new docker image regularly. If this isn't feasible for you we can deploy it on azure for now.

@sacdallago why the thumbs down on @kordianbruck's comment?

**Comment by vviro** [comment]
@Henni If you can easily do this on Azure, by all means please do.

**Comment by sacdallago** [comment]
@Henni 
1. yep, MS is more maintainable and I'd like this to be the long-term solution, so definetly go for it.
2. The API is set up as an [autobuild](https://hub.docker.com/r/musicconnectionmachine/api/) on docker hub so whatever is in ~~develop is there with tag `develop` and whatever is in master is there with tag `latest`, automatically built on merges on either branches~~.
3. The thumbs down was referred to using @vviro 's PG :) I'd like this to be on MS as well, again for maintainability by a larger audience and due to some commitments with MS, but for now it's ok :) We can: dump the data and port it to MS or re-run the scrapers in the future.

**edit**: future === saturday

**edit 2**: I was wrong:

| branch | tag |
| ------------- |:-------------:|
| develop | latest |
| master | master |

**Comment by Henni** [comment]
~~@sacdallago @kordianbruck any idea which type of machine / app / whatever you used for the old API on Azure? It wasn't a normal "web app" app service, as this one doesn't list docker support in its options... (see "mcmapi" in the group "production")~~
nevermind.. finally found it.

**Comment by Henni** [comment]
up and running at http://mcmapi.azurewebsites.net/instruments
connected to @vviro's database and using default API-KEY for now.

**Comment by sacdallago** [comment]
Excellent.
Pinging @MusicConnectionMachine/group-5 and @MusicConnectionMachine/group-6 . Please now try your tools on real data :)

**Comment by vviro** [comment]
@sacdallago Do we have a long-term commitment from MS for the infrastructure for this project?

**Comment by sacdallago** [comment]
@vviro yep :)
